{{- define "titan-mesh-helm-lib-chart.configs.envoy-sds-validation" }}
  {{- $global := $.Values.global  }}
  {{- $globalTitanSideCars := deepCopy ($global.titanSideCars | default dict)  }}
  {{- $titanSideCars := mergeOverwrite $globalTitanSideCars ($.Values.titanSideCars | default dict)  }}
  {{- $envoy := $titanSideCars.envoy  }}
envoy-sds-validation.yaml: |
  resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_sds
    validation_context:
      trusted_ca:
  {{- if $envoy.intTlsCert }}
        filename: {{ printf "%s/ca.crt" ( $envoy.intSecretsFolder | default "/secrets/int" ) }}
  {{- else }}
        filename: {{ printf "%s/ca.crt" ( $envoy.secretsFolder | default "/secrets" ) }}
  {{- end }}
{{- end }}