{{- define "titan-mesh-helm-lib-chart.configs.envoy-sds-validation-pub" }}
  {{- $global := $.Values.global  }}
  {{- $globalTitanSideCars := deepCopy ($global.titanSideCars | default dict)  }}
  {{- $titanSideCars := mergeOverwrite $globalTitanSideCars ($.Values.titanSideCars | default dict)  }}
  {{- $envoy := $titanSideCars.envoy  }}
envoy-sds-validation-pub.yaml: |
  resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_sds_pub
    validation_context:
      trusted_ca:
        filename: {{ $envoy.trustCACertBundlePath | default "/etc/ssl/certs/ca-bundle.trust.crt" }}
{{- end }}